Imports an image from another namespace if possible,
otherwise execute the given closure.

Example:
[source,groovy]
----
odsComponentStageImportOpenShiftImageOrElse(context) {
  stage('Build') {
    // custom stage to build your application package
  }
  odsComponentStageBuildOpenShiftImage(context)
}
----

The stage takes the exact same options as `odsComponentStageImportOpenShiftImage`.

Before running the image import, it checks whether the image (identified by the
`sourceTag`) is present in a suitable project. This is the current
target project, and potentially one or more specified by the pipeline option
`imagePromotionSequences`. For example, if `imagePromotionSequences` is
`['dev->test', 'test->prod']` (which is the default setting), then, given the
current target environment is `test`, suitable environments are `dev` (based on
`dev->test`), and `test` itself.

If the image is not present in a suitable project, the given closure is executed.

Using this "stage" allows you to avoid building a container image for the same
Git commit multiple times, reducing build times and increasing reliability as
you can promote the exact same image from one environment to another. Keep in
mind that image lookup works by finding an image tagged with the current Git
commit. If you merge a branch into another using a merge commit, the current Git
commit will differ from the previously built image tag, even if the actual
contents of the repository are the same. To ensure image importing kicks in, use
the https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---ff[--ff-only] option on `git merge` (this can also be enabled for pull
requests in Bitbucket under "Merge strategies"). There are a few consequences
when doing so, which should be kept in mind:

* No merge commit is created, which has the downside that you do not see when
  a PR was merged, and that the merge commit is a convenient way to find the
  associated PR. However, it has the upside that your Git history is not
  polluted by merge commits.
* Enforcing a fast-forward merge prevents you from merging a branch which is
  not up-to-date with the target branch. This has the downside that before
  merging, you may need to rebase your branch or merge the target branch into
  your branch if someone else updated the target branch in the meantime. While
  this may cause extra work, it has the upside that you cannot accidentally
  break the target branch (e.g. tests on your branch may work based on the
  outdated target branch, but fail after the merge).

In summary, using `git merge --ff-only` provides safety, a clean history and
allows to promote the exact same image between environments.
