= Component Pipeline

This pipeline allows to have a minimal `Jenkinsfile` in each repository by providing all language-agnostic build aspects. The goal is to duplicate as little as possible between repositories and have an easy way to ship updates to all projects.

== Usage

Load the shared library in your `Jenkinsfile` like this:

[source,groovy]
----
@Library('ods-jenkins-shared-library@3.x') _

odsComponentPipeline(
  imageStreamTag: 'ods/jenkins-agent-golang:3.x',
  branchToEnvironmentMapping: [
    'master': 'dev',
    // 'release/': 'test'
  ]
) { context ->
  odsComponentFindOpenShiftImageOrElse(context) {
    stage('Build') {
      // custom stage
    }
    odsComponentStageScanWithSonar(context)
    odsComponentStageBuildOpenShiftImage(context)
  }
  odsComponentStageRolloutOpenShiftDeployment(context)
}
----

The version in `@Library` can be any Git revision, such as a branch (e.g. `master` or `2.x`), a tag (e.g. `v2.0`) or even a specific commit.

There are many built-in stages like `odsComponentStageScanWithSonar` that you can use, please see <<_stages,Stages>> for more details.

include::partial$odsComponentPipeline.adoc[]

== Stages

Each built-in stage (like `odsComponentStageScanWithSonar`) takes two arguments:

- `context` (required, this is the <<_pipeline_context,pipeline context>>)
- `config` (optional, a map of configuration options)

Example:
----
odsComponentStageScanWithSonar(context, [branch: 'production'])
----

=== odsComponentFindOpenShiftImageOrElse

include::partial$odsComponentFindOpenShiftImageOrElse.adoc[leveloffset=+2]

=== odsComponentStageScanWithSonar

include::partial$odsComponentStageScanWithSonar.adoc[leveloffset=+2]

=== odsComponentStageScanWithAqua

include::partial$odsComponentStageScanWithAqua.adoc[leveloffset=+2]

=== odsComponentStageScanWithTrivy

include::partial$odsComponentStageScanWithTrivy.adoc[leveloffset=+2]

=== odsComponentStageScanWithSnyk

include::partial$odsComponentStageScanWithSnyk.adoc[leveloffset=+2]

=== odsComponentStageBuildOpenShiftImage

include::partial$odsComponentStageBuildOpenShiftImage.adoc[leveloffset=+2]

=== odsComponentStageImportOpenShiftImage

include::partial$odsComponentStageImportOpenShiftImage.adoc[leveloffset=+2]

=== odsComponentStageRolloutOpenShiftDeployment

include::partial$odsComponentStageRolloutOpenShiftDeployment.adoc[leveloffset=+2]

=== odsComponentStageUploadToNexus

include::partial$odsComponentStageUploadToNexus.adoc[leveloffset=+2]

=== odsComponentStageCopyImage

include::partial$odsComponentStageCopyImage.adoc[leveloffset=+2]
