package org.ods.core.test.usecase.levadoc.utils

import groovy.util.logging.Slf4j
import org.ods.orchestration.mapper.LeVADocumentParamsMapper
import org.ods.orchestration.util.Project

import static groovy.json.JsonOutput.prettyPrint
import static groovy.json.JsonOutput.toJson

@Slf4j
class LeVADocumentParamsMapperWithLogging extends LeVADocumentParamsMapper {
    LeVADocumentParamsMapperWithLogging(Project project) {
        super(project)
    }

    Map build(Map data = [: ]) {
        Map result
        try {
            result = super.build(data)
        } catch(Throwable e) {
            log.error(e.getMessage(), e)
            throw e
        }

        log.info("--- INPUT GENERATED BY LeVADocumentParamsMapper.build(data) (start) ---")
        log.info(prettyPrint(toJson(result)))
        log.info("--- INPUT GENERATED BY LeVADocumentParamsMapper.build(data) (end) ---")
        return result
    }

    Map buildWithRepositories() {
        Map result
        try {
            result = super.buildWithRepositories()
        } catch(Throwable e) {
            log.error(e.getMessage(), e)
            throw e
        }

        log.info("--- INPUT GENERATED BY LeVADocumentParamsMapper.buildWithRepositories(data) (start) ---")
        log.info(prettyPrint(toJson(result)))
        log.info("--- INPUT GENERATED BY LeVADocumentParamsMapper.buildWithRepositories(data) (end) ---")
        return result
    }

}

