apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: mro-sharedlib
    name: ods-mro-shared-library-${ODS_GIT_REF}
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${ODS_GIT_REF}
        uri: ${REPO_BASE}/opendevstack/ods-mro-jenkins-shared-library.git
      sourceSecret:
        name: cd-user-with-password
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
          - name: ODS_IMAGE_TAG
            value: ${ODS_IMAGE_TAG}
          - name: ODS_GIT_REF
            value: ${ODS_GIT_REF}
      type: JenkinsPipeline
    triggers:
    - generic:
        secret: ${PIPELINE_TRIGGER_SECRET}
      type: Generic
parameters:
- name: ODS_IMAGE_TAG
  required: true
- name: ODS_GIT_REF
  required: true
- name: REPO_BASE
  required: true
- name: PIPELINE_TRIGGER_SECRET
  required: true
